server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.128.0.5:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

